### PR TITLE
Update {{uw-spam1}} label and edit summary

### PR DESCRIPTION
**Pull request by JJMC89**
"spam links" → "inappropriate external links"
Requested at [Wikipedia talk:Twinkle#Edit summary for uw-spam1](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=796122026#Edit_summary_for_uw-spam1)

### CODE REVIEW

**Comment by rchard2scout** [comment]
It looks like the edit summaries have been pulled from [WP:UTM](https://en.wikipedia.org/wiki/Wikipedia:Template_messages/User_talk_namespace), so maybe it should be changed there as well?

**Comment by MusikAnimal** [comment]
What about uw-spam2, 3, 4, 4im?

I otherwise see nothing wrong with this change, and yes I would update WP:UTM, too.

**Comment by JJMC89** [comment]
@MusikAnimal: uw-spam1 doesn't mention spam, only that the links are inappropriate. The rest of the series does. WP:UTM only has the one line for the series, so an single one cannot be changed there.

**Comment by mc10** [comment]
Seems reasonable to me.

**Pull request merged**
