### PR TITLE
various updates to block module, styling tweak to Morebits

### PR DESCRIPTION
**Pull request by MusikAnimal**

### CODE REVIEW

**Comment by MusikAnimal** [comment]
@atlight @azatoth @Amalthea anytime to look this over? The last commit is among the more high-priority fixes. If these pull requests are coming in too quickly, I can either wait and try to fix as many as issues at once in a single pull request, or break them up into smaller ones, whichever is easier for you!

**Comment by atlight** [comment]
Sorry - I'm in the midst of a very busy period right now.

We really need to get you commit access! Would you be comfortable with that? You could still make pull requests whenever you want additional review, but you would of course be able to bypass the  process for straightforward changes like this one. I'll ask AzaToth to add you if you agree.

**Comment by MusikAnimal** [comment]
@atlight That'd be great! I like having the code reviews, but for things I'm a bit more confident about and for more urgent bugs it'd be nice to get it out there and not put a strain on the other collaborators

**Comment by MusikAnimal** [comment]
Thank you!

**Pull request merged**
