### PR TITLE
morebits: Deprecate RegExp.escape in favor of Morebits.string.escapeRegExp

### PR DESCRIPTION
**Pull request by Amorymeltzer**
Part of #910, cc @siddharthvp

### CODE REVIEW

**Comment by siddharthvp** [comment]
Since this is anyway a breaking change, I was thinking it would be worth improving things by enforcing `space_fix` in Morebits.string.escapeRegExp (making it the default and removing the option to turn it off). This does away with the awkward use of `true` as second param. In places where space_fix is not desired, mw.util.escapeRegExp can be used instead, which is anyway shorter.

**Comment by Amorymeltzer** [comment]
That's a good point and one that I only briefly considered, if I'm being honest.  I think I was hoping to make anyone's life easier, but I do think it'd be worthwhile.  This of course predates the mw tool, so it's about damn time.

**Comment by Amorymeltzer** [comment]
{{done}}.  Drew a blank on a different name, still think it'd be clearer.

**Comment by mdaniels5757** [comment]
> {{done}}.

You know templates don't work here, right? :)

Best, ~~~~

**Pull request merged**
