### PR TITLE
morebits: Add YYYYMMDDHHmmss to morebits.date constructor

### PR DESCRIPTION
**Pull request by Amorymeltzer**
Noted at https://github.com/azatoth/twinkle/pull/1194#discussion_r525931042, basically just copied from @siddharthvp's work at mwn: https://github.com/siddharthvp/mwn/blob/7fa804354e817ae5e1d3faad9fea64e86bc0cf90/src/date.ts#L21-L25

### CODE REVIEW

**Comment by siddharthvp** [comment]
Don't put it inside `signatureTimestampFormat` hook as that's for wikis to specify the local signature format. This thing is the same everywhere, so I'd either inline it in the constructor, or create a static function like newFromMWTimestamp() to call from the constructor.

**Comment by Amorymeltzer** [comment]
Ah yeah, duh!  Done, but totally invalidated by #1203, so will rework after that.

**Comment by Amorymeltzer** [comment]
Now redone, and includes #1213.  As noted, the bespoke checks are aimed to be first, since not doing so causes problems.

**Review by siddharthvp — COMMENTED** [review]
> Unfortunately, this limits us in certain ways, in particular the inability to parse the UNIX epoch after late November, 2286.

Height of future planning!

Seriously though, I can't think of any situation where the 14-digit timestamp will arise as a number rather than string. That part could be omitted.

**Comment by Amorymeltzer** [comment]
> Seriously though, I can't think of any situation where the 14-digit timestamp will arise as a number rather than string. That part could be omitted.

Funny, I was just looking at that and writing some tests for it.  Agreed the `typeof` is unneeded; removed.

**Pull request merged**
