### PR TITLE
talkback: Fix capitalization in edit summaries

### LINKED ISSUE #1165: Talkback: Redlink in NPOVN notifications
https://en.wikipedia.org/w/index.php?title=Wikipedia:Neutral_point_of_view/noticeboard&action=history

https://en.wikipedia.org/w/index.php?diff=984391784&diffmode=source

### PR DESCRIPTION
**Pull request by TheTVExpert**
Fixes #1165.

### CODE REVIEW

**Review by Amorymeltzer — CHANGES_REQUESTED** [review]
Thanks for the speedy PR @TheTVExpert!  This looks good to me, but as there's no urgency given creation of the redirect and as long as we're bypassing redirects, feel like taking care of the edit summaries for the others?  That looks to be:

*Wikipedia:Biographies of living persons/Noticeboard
*Wikipedia:External links/Noticeboard
*Wikipedia:Neutral point of view/Noticeboard
*Wikipedia:Reliable sources/Noticeboard

**Comment by Amorymeltzer** [comment]
Just noting these all stem from #1123

**Comment by TheTVExpert** [comment]
Fixed.

**Review by Amorymeltzer — APPROVED** [review]

**Comment by Amorymeltzer** [comment]
Awesome, thanks @TheTVExpert!

**Pull request merged**
