### PR TITLE
friendlytalkback: minor cleanup to getNoticeWikitext

### PR DESCRIPTION
**Pull request by DannyS712**
Use guard clauses instead of needing `if` blocks

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
This is quite welcome!  I can rework #929 to give this precedence, but this is gonna conflict pretty heavily with #908.  I want to get those massive changes though, so let's revisit once that's merged?

**Comment by Amorymeltzer** [comment]
I *think* this got invalidated by the addition of `switch`es in #908, is that right?  Sorry for unspent effort

**Comment by DannyS712** [comment]
> I _think_ this got invalidated by the addition of `switch`es in #908, is that right? Sorry for unspent effort

Nope

**Comment by Amorymeltzer** [comment]
Are the `if`s better than the `switch`, or, sorry, am I missing a different issue?

**Comment by siddharthvp** [comment]
Likewise, not seeing any improvements here after the rebase.

**Pull request closed without merging**
