### PR TITLE
xfd: Notify creator of second template of tfm nomination

### PR DESCRIPTION
**Pull request by martijnhoekstra**
This is hotly requested by TfD regulars, even if it is non-standard for other XfDs

### CODE REVIEW

**Comment by martijnhoekstra** [comment]
@atlight does this settle all issues? Can I squash these?

**Comment by atlight** [comment]
Yes, looks fine, although I haven't tested it. Please squash them into a single commit; that is a definite prerequisite to merging any pull request.

**Comment by atlight** [comment]
Ooh, seems like I forgot about this. Would you still like this to be merged? Have you tested it?

**Comment by martijnhoekstra** [comment]
Yes, I've tested it. It's been ages since I've done anything on Wikipedia though, so I'm not sure if it still functions as intended.

**Comment by martijnhoekstra** [comment]
Thanks for merging thing @Amorymeltzer ! 

Did you check if it still works properly? It's 3 and a half years old by now, so between the time I wrote it and now, things may have broken.

**Comment by Amorymeltzer** [comment]
I did and was pleasantly surprised!  It helps that [none of that code](https://github.com/azatoth/twinkle/blame/10de46eea89c2a27ae3a13d9a63f189e9da33687/modules/twinklexfd.js#L1543-L1557) had changed for at least five years.  I think this just got missed, sorry about that.  I'm not a TfM regular but I imagine they'll appreciate it.

**Comment by martijnhoekstra** [comment]
Ah, good to hear. I wasnt even sure if the process is still the same!

**Comment by Amorymeltzer** [comment]
Just wanted to say, saw this in the wild today, very cool!

**Comment by martijnhoekstra** [comment]
Great to hear, I'm happy it's finding good use.

**Pull request merged**
