### PR TITLE
UNTESTED: Fix #402, fix #424

### LINKED ISSUE #402: Add uw-paid1 to uw-paid4
Could you please add the uw-paid warning templates to the UW module? 

TIA
SoWhy

### LINKED ISSUE #424: Add uw-blank1, uw-blank2
Tracking issue for a problem that is going to be fixed by #412

### PR DESCRIPTION
**Pull request by ToBeFree**
These changes have NOT been tested. I'm just saving you the editing part of the work, not the testing part. 😉 

Maintainers of this project have write access on my patch-3 branch and are welcome to fix any problems before merging.

closes #402, closes #424

### CODE REVIEW

**Comment by SoWhy** [comment]
You might want to check #412 first which includes some of the changes you propose already.

**Comment by ToBeFree** [comment]
Moving the welcome-changes to another request

**Comment by ToBeFree** [comment]
Moved the only remaining change to #426

**Comment by ToBeFree** [comment]
Closing pull request in favor of #412

**Pull request closed without merging**
