### PR TITLE
Remove |static=true ; bring back the bouncy ball!

### PR DESCRIPTION
**Pull request by QEDK**
TTO, you seem to have added the template under much duress. But, PamD still wants the bouncy ball. I guess, we'll give it. xD

### CODE REVIEW

**Comment by atlight** [comment]
Well, I'm not going to merge this, that's for sure...

**Comment by QEDK** [comment]
Hahaha. This was foreseeable.

**Comment by Technical-13** [comment]
I'm not sure adding it here is the best thing (despite the fact that I like the bouncy ball and apply that version myself with my WikiLove ACC helper script) because then all of the people who are use to it applying without the bouncy ball will show up to complain that there shouldn't be any animation and it will simply be a back and forth mess.  I would instead suggest that those people that want it add it as a custom welcome template and be done with it.

**Comment by QEDK** [comment]
There wasn't any discussion to support either of the viewpoints. So.....

**Comment by atlight** [comment]
The discussion petered out, and if I remember correctly, PamD was happy with my proposed solution of using the custom welcome template feature.

**Pull request closed without merging**
