### PR TITLE
General minor clean up

### PR DESCRIPTION
**Pull request by DannyS712**
Move "// notify user" comment to the line directly above the relevant code, separate "Morebits.wiki.removeCheckpoint();" from the chunk of code used for notifications (only whitespace was changed)

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
A lot of this would be better dealt with by some input at #500

**Comment by DannyS712** [comment]
> A lot of this would be better dealt with by some input at #500

I read through that thread - I'm not familiar with ESlint at all, and it seems out of my depth

**Comment by Amorymeltzer** [comment]
It would (among other things) enforce a lot of the stylistic changes here that we have up to now not chosen to prefer, such as spaces after `if` and the like.

**Comment by DannyS712** [comment]
@Amorymeltzer I think I'm done with this round of clean up, if you are willing to merge it

**Comment by siddharthvp** [comment]
I don't think this PR should be accepted as it would result in completely unnecessary merge conflicts with other PRs. Also, I don't agree with many of the changes:
- Capitalisation of others' comments is plain silly. I wouldn't make such changes unless I'm editing the surrounding code or making some overall structural changes.
- Removal of newlines in some places is unnecessary and makes stuff harder to read.
- Changes to styling of if conditions should be handled along with #500, as Amorymeltzer said.

**Comment by DannyS712** [comment]
Okay, then I'll withdrawn this. Sorry for the trouble

**Pull request closed without merging**
