### PR TITLE
tag: add undisclosed paid template

### PR DESCRIPTION
**Pull request by SoWhy**
I'm no expert in JS but this should work. Please see if so

### CODE REVIEW

**Comment by atlight** [comment]
If you can change the commit message to reference the "tag" module I'll gladly merge it. Something like `tag: Add undisclosed paid template`

**Comment by SoWhy** [comment]
Done

**Comment by atlight** [comment]
Also https://en.wikipedia.org/w/index.php?title=Template:Undisclosed_paid/doc&diff=845825018&oldid=821809769

@MusikAnimal could you sync this?

**Comment by MusikAnimal** [comment]
Synced! Along with friendlywelcome and twinkleconfig

**Pull request merged**
