### PR TITLE
xfd/tag: link pages in edit summary/section header where possible

### PR DESCRIPTION
**Pull request by siddharthvp**
Requested at WT:TW

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
Am I wrong or didn't this get brought up in another PR somewhere recently?

**Comment by siddharthvp** [comment]
You must be talking about #829, where I forgot to add the links in the section header. Put that into this PR now.

**Comment by Amorymeltzer** [comment]
Ahh yeah, that'd be it!

**Comment by Amorymeltzer** [comment]
Merged as 8e4a8cb and 5c6dde4 🎉 

Feeling cute, might push live later 😊

**Pull request closed without merging**
